# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-18 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
    ]
