# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-18 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200118_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
